export const COURSE_DETAIL_RECEIVED = 'COURSE_DETAIL_RECEIVED';
export const COURSE_LIST_RECEIVED = 'COURSE_LIST_RECEIVED';
export const COURSE_LIST_ERROR = 'COURSE_LIST_ERROR';

export const REGION_SHOW = 'REGION_SHOW';
export const REGION_HIDE = 'REGION_HIDE';
