export const PROFILE_RECEIVED = 'PROFILE_RECEIVED';
export const PROFILE_CREATE_SENDING = 'PROFILE_CREATE_SENDING';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_ERROR = 'PROFILE_CREATE_ERROR';
