export const PROFILE_RECEIVED = 'PROFILE_RECEIVED';
export const PROFILE_CREATE_SENDING = 'PROFILE_CREATE_SENDING';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_ERROR = 'PROFILE_CREATE_ERROR';

export const PROFILE_UPDATE_SENDING = 'PROFILE_UPDATE_SENDING';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';
