export const CLUB_DETAIL_RECEIVED = 'CLUB_DETAIL_RECEIVED';
export const CLUB_DETAIL_SENDING = 'CLUB_DETAIL_SENDING';
export const CLUB_UPDATE_SUCCESS = 'CLUB_UPDATE_SUCCESS';

export const MEMBER_LIST_RECEIVED = 'MEMBER_LIST_RECEIVED';
export const MEMBER_LIST_ERROR = 'MEMBER_LIST_ERROR';

export const CLUB_LIST_RECEIVED = 'CLUB_LIST_RECEIVED';
export const CLUB_LIST_ERROR = 'CLUB_LIST_ERROR';
