export const CLUB_DETAIL_RECEIVED = 'CLUB_DETAIL_RECEIVED';
export const CLUB_DETAIL_SENDING = 'CLUB_DETAIL_SENDING';
export const CLUB_UPDATE_SUCCESS = 'CLUB_UPDATE_SUCCESS';

export const CURRENT_MEMBERS_RECEIVED = 'CURRENT_MEMBERS_RECEIVED';
export const CURRENT_MEMBERS_ERROR = 'CURRENT_MEMBERS_ERROR';
