export const CLUB_QUALIFICATIONS_RECEIVED = 'CLUB_QUALIFICATIONS_RECEIVED';
export const CLUB_QUALIFICATIONS_ERROR = 'CLUB_QUALIFICATIONS_ERROR';
export const MEMBER_QUALIFICATIONS_RECEIVED = 'MEMBER_QUALIFICATIONS_RECEIVED';
export const MEMBER_QUALIFICATIONS_ERROR = 'MEMBER_QUALIFICATIONS_ERROR';
export const GENERIC_QUALIFICATIONS_ERROR = 'GENERIC_QUALIFICATIONS_ERROR';

export const QUALIFICATION_LIST_RECEIVED = 'QUALIFICATION_LIST_RECEIVED';
export const QUALIFICATION_LIST_ERROR = 'QUALIFICATION_LIST_ERROR';
